// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Mprokazin.DdlLtlf.OnlineDemo.Data;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Mprokazin.DdlLtlf.OnlineDemo.Data.Migrations
{
    [DbContext(typeof(DemoDb))]
    partial class DemoDbModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Mprokazin.DdlLtlf.OnlineDemo.Models.GenerateRun", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<int>("ProjectId")
                        .HasColumnType("integer");

                    b.Property<int>("InputId")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("GeneratedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("InputTokens")
                        .HasColumnType("integer");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("OutputTokens")
                        .HasColumnType("integer");

                    b.HasKey("UserId", "ProjectId", "InputId", "GeneratedAt");

                    b.ToTable("GenerateRuns");
                });

            modelBuilder.Entity("Mprokazin.DdlLtlf.OnlineDemo.Models.Input", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.Property<int>("ProjectId")
                        .HasColumnType("integer");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(65536)
                        .HasColumnType("character varying(65536)");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.ToTable("Inputs");
                });

            modelBuilder.Entity("Mprokazin.DdlLtlf.OnlineDemo.Models.Output", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("ConvertedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("InputId")
                        .HasColumnType("integer");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(65536)
                        .HasColumnType("character varying(65536)");

                    b.HasKey("Id");

                    b.HasIndex("InputId")
                        .IsUnique();

                    b.ToTable("Outputs");
                });

            modelBuilder.Entity("Mprokazin.DdlLtlf.OnlineDemo.Models.Project", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("Mprokazin.DdlLtlf.OnlineDemo.Models.SolveRun", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("DiagnosticsJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Ok")
                        .HasColumnType("boolean");

                    b.Property<int>("ProjectId")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("RanAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.ToTable("SolveRuns");
                });

            modelBuilder.Entity("Mprokazin.DdlLtlf.OnlineDemo.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DailyTokenBudget")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("LastResetUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Mprokazin.DdlLtlf.OnlineDemo.Models.GenerateRun", b =>
                {
                    b.HasOne("Mprokazin.DdlLtlf.OnlineDemo.Models.User", null)
                        .WithMany("GenerateRuns")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Mprokazin.DdlLtlf.OnlineDemo.Models.Input", b =>
                {
                    b.HasOne("Mprokazin.DdlLtlf.OnlineDemo.Models.Project", "Project")
                        .WithMany("Inputs")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("Mprokazin.DdlLtlf.OnlineDemo.Models.Output", b =>
                {
                    b.HasOne("Mprokazin.DdlLtlf.OnlineDemo.Models.Input", "Input")
                        .WithOne("Output")
                        .HasForeignKey("Mprokazin.DdlLtlf.OnlineDemo.Models.Output", "InputId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Input");
                });

            modelBuilder.Entity("Mprokazin.DdlLtlf.OnlineDemo.Models.Project", b =>
                {
                    b.HasOne("Mprokazin.DdlLtlf.OnlineDemo.Models.User", "User")
                        .WithMany("Projects")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Mprokazin.DdlLtlf.OnlineDemo.Models.SolveRun", b =>
                {
                    b.HasOne("Mprokazin.DdlLtlf.OnlineDemo.Models.Project", "Project")
                        .WithMany("SolveRuns")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("Mprokazin.DdlLtlf.OnlineDemo.Models.Input", b =>
                {
                    b.Navigation("Output");
                });

            modelBuilder.Entity("Mprokazin.DdlLtlf.OnlineDemo.Models.Project", b =>
                {
                    b.Navigation("Inputs");

                    b.Navigation("SolveRuns");
                });

            modelBuilder.Entity("Mprokazin.DdlLtlf.OnlineDemo.Models.User", b =>
                {
                    b.Navigation("GenerateRuns");

                    b.Navigation("Projects");
                });
#pragma warning restore 612, 618
        }
    }
}
